name: Full Test
on: pull_request
jobs:
  full-test:
    runs-on: ubuntu-18.04
    steps:
    - run: sudo apt install tcl-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: ./sqlite/configure
    - run: make fulltest
